version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: mvn clean compile
  test:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: mvn verify
  deploy:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: PGP_RINGS="$(echo ${PGP_RINGS_ENCODED} | base64 --decode)" mvn deploy -P deploy -s settings.xml

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            branches:
              only: /.*/
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
